### ISSUE TITLE
Traceback error in "ssp.yaml"

### ISSUE THREAD

**Issue by abdulhameed-lm** [chipsalliance/Cores-SweRV-Support-Package#4]
Hi,
I tried running ssp by following the instructions given in README.md as follows:

1- git clone https://github.com/Codasip/SweRV-Support-Package-free.git
2- cd SweRV-Support-Package-free/
3- python3 -m pip install -r requirements.txt . --user
4- ssp run

but i get following **errors**:
WARNING: No swap limit support
Traceback (most recent call last):
  File "/home/username/.local/bin/ssp", line 11, in <module>
    sys.exit(ssp())
  File "/home/username/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/username/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/ssp/cli/__init__.py", line 27, in run
    launcher.run(sshx, dry_run, skip_config)
  File "/home/username/.local/lib/python3.6/site-packages/ssp/launcher.py", line 53, in test_docker_installation
    return function(*args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/ssp/launcher.py", line 177, in run
    self.config = yaml.load(fp, Loader=Loader)
  File "/home/username/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/username/.local/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:10484)
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:10831)
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:11813)
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:13717)
  File "ext/_yaml.pyx", line 732, in _yaml.CParser._compose_node (ext/_yaml.c:10932)
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:13923)
yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "ssp.yaml", line 17, column 5

Following is my **ssp.yaml file**:
from_image: "ssp-docker-registry.codasip.com/free/distrib-ssp-seh1-free:latest"
new_image: "custom-ssp"
drives:
symlinks:
groups:
    # groupname: gid
    	domain users: 967000513
	sudo: 27
 	docker: 130
users:
      - name: username
        uid: 967002735
        gid: 967000513
	groups:
         domain users: 967000513
         sudo: 27
	 docker: 130

export:
    - CPM_ALWAYS_CONFIGURE=True
    - PATH=$PATH:/prj/ssp/common/bin

Can you guide me where am I wrong?

**Comment by tenondra** [comment]
Hi, could you please try removing all lines that start with domain and report back?

**Comment by abdulhameed-lm** [comment]
i removed the domain name lines, replaced them with username

**Comment by tenondra** [comment]
Try running the ssp with new modified ssp.yaml please. The issue was probably caused by the 'domain' key, which is and unknown key for ssp launcher.

**Comment by abdulhameed-lm** [comment]
i am working on a domain user. I dont have access to sudo otherwise. Can't i run it with domain login(@abc.com)?

**Comment by tenondra** [comment]
Just to be clear, all the credentials you specify for ssp in ssp.yaml are free for you to choose, except username, which has to correspond with your linux username (whatever preceeds the @).

**Comment by abdulhameed-lm** [comment]
I changed my username in ssp as follow:
![image](https://user-images.githubusercontent.com/73219099/106552305-dcaf9300-6538-11eb-95f4-f25e8dcb006f.png)
still getting same errors.

WARNING: No swap limit support
Traceback (most recent call last):
  File "/home/abdulhameed.akram/.local/bin/ssp", line 11, in <module>
    sys.exit(ssp())
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/ssp/cli/__init__.py", line 27, in run
    launcher.run(sshx, dry_run, skip_config)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/ssp/launcher.py", line 53, in test_docker_installation
    return function(*args, **kwargs)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/ssp/launcher.py", line 177, in run
    self.config = yaml.load(fp, Loader=Loader)
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/abdulhameed.akram/.local/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:10484)
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:10831)
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:11813)
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:13717)
  File "ext/_yaml.pyx", line 732, in _yaml.CParser._compose_node (ext/_yaml.c:10932)
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:13923)
yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "ssp.yaml", line 7, column 5

**Comment by tenondra** [comment]
This should be correct ssp.yaml, hope it helps
```yaml
from_image: "ssp-docker-registry.codasip.com/free/distrib-ssp-seh1-free:latest"
new_image: "custom-ssp"
groups:
    doman_users@lmlhr: 967000513
    dcengineers: 967002961
users:
    -   name: abdulhameed.akram
        uid: 967002735
        gid: 967000513
        groups:
          - 967002961
          - 27
          - 130

drives:
symlinks:
copyfiles:
export:
    - CPM_ALWAYS_CONFIGURE=True
    - PATH=$PATH:/prj/ssp/common/bin
```
